apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: game-service
  name: game-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: game-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: game-service
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: raphaelruoff/game-service:1.0
          name: game-service
          ports:
            - containerPort: 9093
              protocol: TCP
      restartPolicy: Always
