apiVersion: v1
kind: Service
metadata:
  name: leaderboard-service
  labels:
    app: leaderboard-service
spec:
  selector:
    app: leaderboard-service
  ports:
    - name: http
      port: 9094
      targetPort: 9094
  type: ClusterIP