apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: leaderboard-service
  name: leaderboard-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: leaderboard-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: leaderboard-service
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/leaderboard
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          image: raphaelruoff/leaderboard-service:1.0
          name: leaderboard-service
          ports:
            - containerPort: 9094
              protocol: TCP
      restartPolicy: Always
