apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: log-service
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: log-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: log-service
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_DATABASE
              value: logging
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          image: raphaelruoff/log-service:1.0
          name: log-service
          ports:
            - containerPort: 9098
              protocol: TCP
          volumeMounts:
            - mountPath: /app/export
              name: log-service-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: log-service-cm0
          name: log-service-cm0
