apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: profile-service
  name: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profile-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: profile-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres123
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/profile
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
          image: raphaelruoff/profile-service:1.0
          name: profile-service
          ports:
            - containerPort: 9095
              protocol: TCP
      restartPolicy: Always
