apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: websocket-service
  name: websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: websocket-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: websocket-service
    spec:
      containers:
        - env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          image: raphaelruoff/websocket-service:1.0
          name: websocket-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
